"""Initial creation of activity tracking tables

Revision ID: 73c57e54e98f
Revises: 
Create Date: 2025-07-17 21:26:12.464839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c57e54e98f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_records',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False, comment='用户加入服务器的时间 (UTC)'),
    sa.PrimaryKeyConstraint('user_id', 'guild_id'),
    sa.UniqueConstraint('user_id', 'guild_id', name='_user_guild_uc')
    )
    op.create_table('tracked_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='Discord 帖子的 ID'),
    sa.Column('author_id', sa.BigInteger(), nullable=False, comment='发帖人 ID'),
    sa.Column('parent_channel_id', sa.BigInteger(), nullable=False, comment='帖子所在的父频道 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index(op.f('ix_tracked_posts_author_id'), 'tracked_posts', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_posts_author_id'), table_name='tracked_posts')
    op.drop_table('tracked_posts')
    op.drop_table('join_records')
    # ### end Alembic commands ###
