# docker-compose.deploy.yml (用于远程部署)
version: '3.8'

services:
  rolebot:
    image: role_bot-rolebot:latest # <-- 部署时使用这个镜像
    container_name: rolebot
    restart: unless-stopped
    volumes:
      [rolebot_data:/app/data]
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_BOT_PROXY=${DISCORD_BOT_PROXY:-}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  rolebot_data: