"""Initial creation of honor system tables

Revision ID: bed6cfc4c97b
Revises: 
Create Date: 2025-07-07 22:22:01.269906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed6cfc4c97b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honor_definitions',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='荣誉名称'),
    sa.Column('description', sa.String(length=255), nullable=False, comment='荣誉描述'),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('guild_id', 'name', name='_guild_name_uc')
    )
    op.create_index(op.f('ix_honor_definitions_guild_id'), 'honor_definitions', ['guild_id'], unique=False)
    op.create_table('tracked_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='Discord 帖子的 ID'),
    sa.Column('author_id', sa.BigInteger(), nullable=False, comment='发帖人 ID'),
    sa.Column('parent_channel_id', sa.BigInteger(), nullable=False, comment='帖子所在的父频道 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index(op.f('ix_tracked_posts_author_id'), 'tracked_posts', ['author_id'], unique=False)
    op.create_table('user_honors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('honor_uuid', sa.String(length=36), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['honor_uuid'], ['honor_definitions.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_honors_user_id'), 'user_honors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_honors_user_id'), table_name='user_honors')
    op.drop_table('user_honors')
    op.drop_index(op.f('ix_tracked_posts_author_id'), table_name='tracked_posts')
    op.drop_table('tracked_posts')
    op.drop_index(op.f('ix_honor_definitions_guild_id'), table_name='honor_definitions')
    op.drop_table('honor_definitions')
    # ### end Alembic commands ###
