"""Remove unique constraint on honor name

Revision ID: 098296053a4b
Revises: b27da8c1830c
Create Date: 2025-10-29 22:25:28.382397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098296053a4b'
down_revision: Union[str, Sequence[str], None] = 'b27da8c1830c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honor_definitions', schema=None) as batch_op:
        batch_op.drop_constraint('_guild_name_uc', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honor_definitions', schema=None) as batch_op:
        batch_op.create_unique_constraint('_guild_name_uc', ['guild_id', 'name'])
    # ### end Alembic commands ###
