"""Add hidden_until_earned to HonorDefinition and update honor rules for anniversary

Revision ID: 64014e84243f
Revises: bed6cfc4c97b
Create Date: 2025-07-13 20:21:29.431638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64014e84243f'
down_revision: Union[str, Sequence[str], None] = 'bed6cfc4c97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_records',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False, comment='用户加入服务器的时间 (UTC)'),
    sa.PrimaryKeyConstraint('user_id', 'guild_id'),
    sa.UniqueConstraint('user_id', 'guild_id', name='_user_guild_uc')
    )
    op.add_column('honor_definitions', sa.Column('hidden_until_earned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honor_definitions', 'hidden_until_earned')
    op.drop_table('join_records')
    # ### end Alembic commands ###
