"""Remove tracked_posts and join_records

Revision ID: b27da8c1830c
Revises: 64014e84243f
Create Date: 2025-07-17 21:27:46.168399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27da8c1830c'
down_revision: Union[str, Sequence[str], None] = '64014e84243f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_records')
    op.drop_index(op.f('ix_tracked_posts_author_id'), table_name='tracked_posts')
    op.drop_table('tracked_posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.Column('parent_channel_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index(op.f('ix_tracked_posts_author_id'), 'tracked_posts', ['author_id'], unique=False)
    op.create_table('join_records',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('guild_id', sa.BIGINT(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'guild_id'),
    sa.UniqueConstraint('user_id', 'guild_id', name=op.f('_user_guild_uc'))
    )
    # ### end Alembic commands ###
